### PR TITLE
use basedriver instead of mjsonwp

### PR DESCRIPTION
**Pull request by jlipps**

### CODE REVIEW

**Comment by jlipps** [comment]
tests failed locally but might not be related, let's see what ci says...

**Comment by jlipps** [comment]
```
  1) sendKey should work with strategy: grouped:
     JavaScriptError: target.frontMostApp().keyboard() failed to tap 'o'
      at errorFromCode (lib/mjsonwp/errors.js:362:12)
      at Object.cb (lib/uiauto-client.js:49:29)
      at Socket.<anonymous> (lib/uiauto-client.js:102:31)
      at _stream_readable.js:908:16
```

flake? going to rerun

**Comment by jlipps** [comment]
ah, worked in the push build. calling the other one a flake.

**Comment by imurchie** [comment]
I'd say you're probably right.

And yay! Awesome on getting that into here!

**Pull request merged**
