### PR TITLE
9.1 beta 2: Accept/dismiss fix

### PR DESCRIPTION
**Pull request by scottdixon**

### CODE REVIEW

**Comment by scottdixon** [comment]
@imurchie

**Comment by imurchie** [comment]
Looks good.

**Comment by amake** [comment]
This should actually be checking for `>= 9` per discussion at appium/appium/issues/5463.

**Comment by scottdixon** [comment]
`test/functional/ios/testapp/autoaccept-alerts/` pass on iOS 9.0

@amake  - do these tests pass for you on iOS 9.0 before the `>= 9` change? Also, which version of Xcode are you running?

Regardless, after changing the conditional to `>= 9`, tests continue to pass for me on both iOS 9 and iOS 9.1, so I guess it makes sense to implement - but before we do, we should investigate the abnormality further to understand why it's failing on *some* iOS 9.

**Pull request merged**
